# Generated by Django 2.0.7 on 2021-05-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='child',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='startdate',
        ),
    ]
