# Generated by Django 2.0.7 on 2021-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210513_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='phone_number',
            field=models.CharField(default='chalyoo', max_length=100),
        ),
    ]
