# Generated by Django 2.0.7 on 2021-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_mymodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.CharField(default='chalyoo', max_length=100),
        ),
    ]
