# Generated by Django 2.0.7 on 2021-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_mymodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='adult',
            field=models.CharField(default='chalyoo', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='child',
            field=models.CharField(default='chalyoo', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='destination',
            field=models.CharField(default='chalyoo', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='startdate',
            field=models.CharField(default='chalyoo', max_length=100),
        ),
    ]
