# Generated by Django 2.0.7 on 2021-05-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20210513_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Destination name', max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('feature1', models.CharField(default='feature1', max_length=100)),
                ('feature2', models.CharField(default='feature1', max_length=100)),
                ('feature3', models.CharField(default='feature1', max_length=100)),
                ('feature4', models.CharField(default='feature1', max_length=100)),
                ('feature5', models.CharField(default='feature1', max_length=100)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
