# Generated by Django 2.0.7 on 2021-05-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Booking',
        ),
    ]
